In [1]:
import numpy as np

<div dir='rtl'>
    مقدار نرم درجه 3 بردار u را محاسبه کنید.
u = (3, 1, 0, 5)
</div>

In [4]:
u = np.array([3,1,0,5])
(np.linalg.norm(u,3)).round(3)

np.float64(5.348)

<div dir='rtl'>
    *
۶
دترمینان وارون ماتریس A کدام است؟

![سوال](h4-06.png "Title")
</div>

In [10]:
A= np.array([[2,-1,1],[0,-1,1],[-1,1,0]])

In [19]:
A_inv = np.linalg.inv(A)

In [20]:
print(np.linalg.det(A_inv))

-0.5


<div dir='rtl'>
    *
۸
دستگاه معادلات خطی زیر را حل کنید. مقدار x1 کدام است؟
</div>
 
![سوال 8](h4-08.png "Title")

In [63]:
A = np.array([[1,3,5],
              [2,4,0],
              [0,7,9]])
b = np.array([[12],[-1],[-2]])
x= np.linalg.solve(A,b)
print(x)

[[ 8.92307692]
 [-4.71153846]
 [ 3.44230769]]


In [64]:
np.dot(A,x)

array([[12.],
       [-1.],
       [-2.]])

<div dir='rtl'>
    *
۹
یک ماتریس با 5 ردیف و 6 ستون بسازید که اعداد بین 1 تا 3 با فاصله یکنواخت از هم به صورت ستونی آن را پر کرده‌اند. میانگین درایه‌های ستون آخر کدام است؟
</div>

In [91]:
m =(((np.linspace(1,3,num=30)).reshape(6,5))).T
print(m.round(2))

[[1.   1.34 1.69 2.03 2.38 2.72]
 [1.07 1.41 1.76 2.1  2.45 2.79]
 [1.14 1.48 1.83 2.17 2.52 2.86]
 [1.21 1.55 1.9  2.24 2.59 2.93]
 [1.28 1.62 1.97 2.31 2.66 3.  ]]


In [93]:
m[:,-1].mean().round(2)

np.float64(2.86)

<div dir='rtl'>
    *
۱۰
اگر بردار u = (2, 3)  را 30 درجه پاد ساعتگرد دوران دهید، مختصات بردار دوران‌یافته کدام است؟ 
</div>

In [104]:
u = np.array([2,3])
R = np.array([[np.cos(np.pi/180*30),-1 * np.sin(np.pi/180*30)],[np.sin(np.pi/180*30),np.cos(np.pi/180*30)]])
np.dot(R,u)

array([0.23205081, 3.59807621])

In [107]:
rad = np.deg2rad(30)
R = np.array([[np.cos(rad),-1 * np.sin(rad)],[np.sin(deg),np.cos(rad)]])
np.dot(R,u)

array([0.23205081, 3.59807621])