# Linear Algebra with Numpy

## Data Science, Machine Learning and Artificial Intelligence - by Farzad Minooei

## Numpy

NumPy (Numerical Python) is one of the core packages for numerical computing in Python.

Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

Check NumPy documentation: https://numpy.org/doc/stable/user/absolute_beginners.html

In [5]:
#Import Numpy library
import numpy as np
#Get the version of numpy
print(np.__version__)

1.26.4


### Vector

In [7]:
#Vector: One-dimension array
u = np.array([3, 4, 0])
u

array([3, 4, 0])

In [8]:
#Type
type(u)

numpy.ndarray

In [9]:
#Shape
u.shape

(3,)

In [10]:
#Indexing
u[0]

3

In [11]:
u[0 : 2]

array([3, 4])

In [12]:
u[[0, 2]]

array([3, 0])

In [13]:
u[-1]

0

In [14]:
#Modify an array
print(u)
u[0] = -3
print(u)

[3 4 0]
[-3  4  0]


In [15]:
#Norms of a vector 
#L2 (Euclidean distance)
np.linalg.norm(u)

5.0

In [16]:
#L1
np.linalg.norm(u, 1)

7.0

In [17]:
#Lp (p = 5)
np.linalg.norm(u, 5)

4.174027662897746

In [18]:
v = np.array([-2, 0, 1])

In [19]:
#Dot product u.v
print(u, v)
np.dot(u, v)

[-3  4  0] [-2  0  1]


6

***Note: The elements of a NumPy array must all be of the same type, whereas the elements of a Python list can be of completely different types.

In [21]:
#Data type
u.dtype

dtype('int32')

In [22]:
a = np.array(['a', 'b', 't'])
print(a)
print(a.dtype) #Unicode string

['a' 'b' 't']
<U1


### Matrix

In [24]:
A = np.array([[1, 3, 5], 
              [0, 2, 6], 
              [3, 1, 9]])
A

array([[1, 3, 5],
       [0, 2, 6],
       [3, 1, 9]])

In [25]:
#Shape
A.shape

(3, 3)

In [26]:
#Indexing
A[0, 1]

3

In [27]:
#Extract a row
A[0]

array([1, 3, 5])

In [28]:
#Extract a row
A[0, :]

array([1, 3, 5])

In [29]:
#Extract a column
A[:, 0]

array([1, 0, 3])

In [30]:
A[1 :, 1:]

array([[2, 6],
       [1, 9]])

In [31]:
#Modify an array
print(A)
A[1, 2] = 0
print(A)

[[1 3 5]
 [0 2 6]
 [3 1 9]]
[[1 3 5]
 [0 2 0]
 [3 1 9]]


### Matrix Operations

In [33]:
#Transpose of A
A.T

array([[1, 0, 3],
       [3, 2, 1],
       [5, 0, 9]])

In [34]:
#Matrix-Scalar multiplication
A * 0.5

array([[0.5, 1.5, 2.5],
       [0. , 1. , 0. ],
       [1.5, 0.5, 4.5]])

In [35]:
#Matrix-Vector multiplication (dot product)
print(A, v)
np.dot(A, v)

[[1 3 5]
 [0 2 0]
 [3 1 9]] [-2  0  1]


array([3, 0, 3])

In [36]:
B = np.array([[1, 0, -1], 
              [1, -2, 0],
              [0, 0, -1]])
B

array([[ 1,  0, -1],
       [ 1, -2,  0],
       [ 0,  0, -1]])

In [37]:
#Matrix-Matrix multiplication (dot product)
np.dot(A, B)

array([[  4,  -6,  -6],
       [  2,  -4,   0],
       [  4,  -2, -12]])

In [38]:
#Inverse of a matrix
A_inv = np.linalg.inv(A)
A

array([[1, 3, 5],
       [0, 2, 0],
       [3, 1, 9]])

In [39]:
#A * A_inv = I
np.dot(A, A_inv).astype(int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [40]:
#Determinant of a matrix
np.linalg.det(A)

-12.000000000000005

In [41]:
#Matrix-Scalar addition
A + 2

array([[ 3,  5,  7],
       [ 2,  4,  2],
       [ 5,  3, 11]])

In [42]:
#Matrix addition
A + B

array([[2, 3, 4],
       [1, 0, 0],
       [3, 1, 8]])

In [43]:
#Matrix-Matrix multiplication (Hadamard product)
A * B

array([[ 1,  0, -5],
       [ 0, -4,  0],
       [ 0,  0, -9]])

In [44]:
#Boolian operations
print(A)
print(A > 1)

[[1 3 5]
 [0 2 0]
 [3 1 9]]
[[False  True  True]
 [False  True False]
 [ True False  True]]


In [45]:
#Extract elements of an array with boolian operation
A[A > 1]

array([3, 5, 2, 3, 9])

In [46]:
#  &: and
#  |: or
#  ~: not
A[(A % 3 == 0) & (A > 4)]

array([9])

In [47]:
A[(A < 1) | (A > 4)]

array([5, 0, 0, 9])

In [48]:
#Concatenate horizontally (column wise)
print(A)
print(B)
np.hstack((A, B))

[[1 3 5]
 [0 2 0]
 [3 1 9]]
[[ 1  0 -1]
 [ 1 -2  0]
 [ 0  0 -1]]


array([[ 1,  3,  5,  1,  0, -1],
       [ 0,  2,  0,  1, -2,  0],
       [ 3,  1,  9,  0,  0, -1]])

In [49]:
#Concatenate vertically (row wise)
print(A)
print(B)
np.vstack((A, B))

[[1 3 5]
 [0 2 0]
 [3 1 9]]
[[ 1  0 -1]
 [ 1 -2  0]
 [ 0  0 -1]]


array([[ 1,  3,  5],
       [ 0,  2,  0],
       [ 3,  1,  9],
       [ 1,  0, -1],
       [ 1, -2,  0],
       [ 0,  0, -1]])

In [50]:
#axis = 0 : concatenate vertically
#axis = 1 : concatenate horizontally
np.concatenate((A, B), axis = 0)

array([[ 1,  3,  5],
       [ 0,  2,  0],
       [ 3,  1,  9],
       [ 1,  0, -1],
       [ 1, -2,  0],
       [ 0,  0, -1]])

### Different Types of Arrays

In [52]:
#An array filled with zeros
a1 = np.zeros((2, 3), dtype = int)
a1

array([[0, 0, 0],
       [0, 0, 0]])

In [53]:
#An array filled with fill_value
a2 = np.full((3, 3), 1, dtype = int)
a2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [54]:
#Create ranges with arange
a3 = np.arange(1, 20, 3)
a3

array([ 1,  4,  7, 10, 13, 16, 19])

In [55]:
a4 = np.arange(5)
a4

array([0, 1, 2, 3, 4])

In [56]:
#Create floating-point ranges with linspace
a5 = np.linspace(1, 5, 30)
a5

array([1.        , 1.13793103, 1.27586207, 1.4137931 , 1.55172414,
       1.68965517, 1.82758621, 1.96551724, 2.10344828, 2.24137931,
       2.37931034, 2.51724138, 2.65517241, 2.79310345, 2.93103448,
       3.06896552, 3.20689655, 3.34482759, 3.48275862, 3.62068966,
       3.75862069, 3.89655172, 4.03448276, 4.17241379, 4.31034483,
       4.44827586, 4.5862069 , 4.72413793, 4.86206897, 5.        ])

In [57]:
a5.shape

(30,)

In [58]:
a5 = a5.reshape(5, 6)
a5

array([[1.        , 1.13793103, 1.27586207, 1.4137931 , 1.55172414,
        1.68965517],
       [1.82758621, 1.96551724, 2.10344828, 2.24137931, 2.37931034,
        2.51724138],
       [2.65517241, 2.79310345, 2.93103448, 3.06896552, 3.20689655,
        3.34482759],
       [3.48275862, 3.62068966, 3.75862069, 3.89655172, 4.03448276,
        4.17241379],
       [4.31034483, 4.44827586, 4.5862069 , 4.72413793, 4.86206897,
        5.        ]])

In [59]:
a5.shape

(5, 6)

In [60]:
#Create an array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.seed(123)
a6 = np.random.normal(0, 1, 30)
print(a6)
print(a6.shape)

[-1.0856306   0.99734545  0.2829785  -1.50629471 -0.57860025  1.65143654
 -2.42667924 -0.42891263  1.26593626 -0.8667404  -0.67888615 -0.09470897
  1.49138963 -0.638902   -0.44398196 -0.43435128  2.20593008  2.18678609
  1.0040539   0.3861864   0.73736858  1.49073203 -0.93583387  1.17582904
 -1.25388067 -0.6377515   0.9071052  -1.4286807  -0.14006872 -0.8617549 ]
(30,)


In [61]:
#Create a 3x3 array of random integers in the interval [0, 10)
np.random.seed(123)
a7 = np.random.randint(0, 10, (3, 3))
a7

array([[2, 2, 6],
       [1, 3, 9],
       [6, 1, 0]])

### Statistics

In [63]:
#Find the mean of array
np.mean(a7)

3.3333333333333335

In [64]:
#Find the standard deviation of array
np.std(a7)

2.8284271247461903

In [65]:
#Find the maximum value
np.max(a7)

9

In [66]:
#Find the minimum value
np.min(a7)

0

In [67]:
#Find sum
np.sum(a7)

30

In [68]:
#Sum along rows (sum over columns)
np.sum(a7, axis = 0)

array([ 9,  6, 15])

In [69]:
#Sum along columns (sum over rows)
np.sum(a7, axis = 1)

array([10, 13,  7])

### Example: Min-Max Scaling

Write a function to scale an array so the values range exactly between 0 and 1.

In [72]:
#Create an array
np.random.seed(123)
a = np.random.randint(1, 1000, 50)
a

array([511, 366, 383, 323, 989,  99, 743,  18, 596, 107, 124, 570, 215,
       738,  97, 114, 639,  48,  74, 545, 943, 225, 112, 410, 340, 847,
       254, 421, 609, 209,  69, 818, 824, 452,   3, 341,  40, 323, 597,
       560, 505, 958, 177, 136, 874, 100, 381, 861, 181, 359])

In [73]:
#Min-max scaling function
def min_max_scaling(x):
    return (x - np.min(x)) / (np.max(x) - np.min(x))

In [74]:
#Apply min-max scaling function
min_max_scaling(a)

array([0.51521298, 0.36815416, 0.38539554, 0.32454361, 1.        ,
       0.09736308, 0.7505071 , 0.01521298, 0.60141988, 0.10547667,
       0.12271805, 0.57505071, 0.21501014, 0.74543611, 0.09533469,
       0.11257606, 0.64503043, 0.04563895, 0.07200811, 0.54969574,
       0.95334686, 0.22515213, 0.11054767, 0.4127789 , 0.34178499,
       0.85598377, 0.25456389, 0.42393509, 0.61460446, 0.20892495,
       0.06693712, 0.82657201, 0.8326572 , 0.45537525, 0.        ,
       0.34279919, 0.03752535, 0.32454361, 0.60243408, 0.56490872,
       0.50912779, 0.96855984, 0.17647059, 0.13488844, 0.88336714,
       0.09837728, 0.38336714, 0.87018256, 0.18052738, 0.36105477])

### Example: Solve Systems of Linear Equations

Ax = b

  x1 + 3 x2 =  4

2 x1 - 4 x2 = -1

In [77]:
A = np.array([[1, 3], 
              [2, -4]])
A

array([[ 1,  3],
       [ 2, -4]])

In [78]:
b = np.array([[4], 
              [-1]])
b

array([[ 4],
       [-1]])

In [79]:
#Check determinant of A
np.linalg.det(A)

-9.999999999999998

In [80]:
#Slove linear equations
x = np.linalg.solve(A, b)
x

array([[1.3],
       [0.9]])

In [81]:
#Check the results
np.dot(A, x)

array([[ 4.],
       [-1.]])

## List vs. Array Performance

In [83]:
l = list(range(60000000))

In [84]:
a = np.arange(60000000)

In [85]:
#List
import time
t_start = time.time() #https://www.unixtimestamp.com/
s = sum(l)
t_end = time.time()
print(s)
print('The processing time is {0:0.5f} seconds'.format(t_end - t_start))

1799999970000000
The processing time is 25.09510 seconds


In [86]:
#Array
t_start = time.time()
s = np.sum(a, dtype = np.int64)
t_end = time.time()
print(s)
print('The processing time is {0:0.5f} seconds'.format(t_end - t_start))

1799999970000000
The processing time is 0.65407 seconds


# End of Code